### PR TITLE
add mbedtls support

### PR DESCRIPTION
**Pull request by bugparty**

### CODE REVIEW

**Comment by Javernaut** [comment]
@bugparty Why have you picked exactly the mbedtls? I see there are 4 possible libraries for https enabling:
- libtls
- openssl
- gnutls
- mbedtls

What is your reasoning?

**Comment by bugparty** [comment]
mbedtls is the easiest one to build, gnutls and openssl is not easy to
compile in android.

Oleksandr Berezhnyi ***@***.***> 于2022年6月20日周一 19:41写道：

**Comment by bugparty** [comment]
openssl and gnutls is not using autoconf, instead they use custom build scripts, I can not make them easily, but mbedtls uses cmake, this project has cmake template so it is easy to build.
besides, mbedtls is an execellent alternative to openssl.

**Review by Javernaut — CHANGES_REQUESTED** [review]
Sorry for the delay. Too many things to do for the main job.

I'd like to ask you to fix a couple of things:

1. No need to add a separate android.cmake file like this. The NDK’s android.toolchain.cmake file already enables the usage of NEON in case of building for armeabi-v7a. So please use android.toolchain.cmake file directly. I used a separate android.cmake for libaom because its cmake configuration wasn't fully compatible with NDK's cmake script.
2. I don't like the way `--enable-protocol=https --enable-version3` flags are added to ffmpeg. I would ask you to:
- Remove FFMPEG_MBEDTLS_ENABLED variable completely
- Refactor EXTRA_BUILD_CONFIGURATION_FLAGS variable to be available for all libraries for a given ABI (just as FFMPEG_EXTRA_LD_FLAGS)
- Append the EXTRA_BUILD_CONFIGURATION_FLAGS with `--enable-protocol=https --enable-version3` in mbedtls/build.sh

**Comment by bugparty** [comment]
OK, got it, I was a little bit worried about your safety last week.
have a nice day:)

**Comment by bugparty** [comment]
Please review,all the requirements are fullfilled

**Review by Javernaut — APPROVED** [review]

**Pull request merged**
